In [3]:
from datasets import load_dataset
dataset_twitter = load_dataset("Jacobvs/CelebrityTweets")

Downloading and preparing dataset parquet/Jacobvs--CelebrityTweets to /Users/ivan/.cache/huggingface/datasets/Jacobvs___parquet/Jacobvs--CelebrityTweets-de2be27b448e7442/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec...

Downloading data files:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading data:   0%|          | 0.00/1.37M [00:00<?, ?B/s]

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Dataset parquet downloaded and prepared to /Users/ivan/.cache/huggingface/datasets/Jacobvs___parquet/Jacobvs--CelebrityTweets-de2be27b448e7442/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec. Subsequent calls will reuse this data.

  0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
import pandas as pd
import ast
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [9]:
df = pd.DataFrame(dataset_twitter)

In [17]:
df = pd.read_csv("twitter.csv")
df.head()

   Unnamed: 0                                              train
0           0  {'index': 0, 'date': '2022-12-01 19:24:25', 'i...
1           1  {'index': 1, 'date': '2022-09-07 01:14:34', 'i...
2           2  {'index': 2, 'date': '2022-07-07 19:33:51', 'i...
3           3  {'index': 3, 'date': '2022-02-16 03:05:25', 'i...
4           4  {'index': 4, 'date': '2021-12-30 22:33:21', 'i...

In [16]:
df["train"] = df["train"].apply(ast.literal_eval)

tweets = pd.json_normalize(df["train"])

tweets.head()

   index  ...                                               text
0      0  ...  long time coming and excited to finally announ...
1      1  ...                            https://t.co/qRY7ltRkV0
2      2  ...  1 year of preparation 🔥 @FreeFire_NA #GarenaFr...
3      3  ...  Go for the Gold, Ladies!!!!!! Cannot wait to w...
4      4  ...      The countdown begins… https://t.co/S5qZP92Ziz

[5 rows x 5 columns]

In [18]:
tweets = tweets[tweets["username"].isin(["elonmusk", "justinbieber"])]

tweets = tweets[["username", "text"]]
tweets.head()

       username                                               text
0  justinbieber  long time coming and excited to finally announ...
1  justinbieber                            https://t.co/qRY7ltRkV0
2  justinbieber  1 year of preparation 🔥 @FreeFire_NA #GarenaFr...
3  justinbieber  Go for the Gold, Ladies!!!!!! Cannot wait to w...
4  justinbieber      The countdown begins… https://t.co/S5qZP92Ziz

In [19]:


def clean_text(text):
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"#\w+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

tweets["text"] = tweets["text"].apply(clean_text)

tweets = tweets[tweets["text"] != ""]

In [21]:
from sklearn.model_selection import train_test_split

X = tweets["text"]
y = tweets["username"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [22]:
vectorizer = TfidfVectorizer(ngram_range=(1,3))

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [23]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_vec, y_train)

pred_lr = lr.predict(X_test_vec)

print("Accuracy:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr))

Accuracy: 0.8153846153846154
              precision    recall  f1-score   support

    elonmusk       0.75      0.94      0.83        32
justinbieber       0.92      0.70      0.79        33

    accuracy                           0.82        65
   macro avg       0.83      0.82      0.81        65
weighted avg       0.84      0.82      0.81        65

In [24]:
nb = MultinomialNB()
nb.fit(X_train_vec, y_train)

pred_nb = nb.predict(X_test_vec)

print("Accuracy:", accuracy_score(y_test, pred_nb))
print(classification_report(y_test, pred_nb))

Accuracy: 0.8
              precision    recall  f1-score   support

    elonmusk       0.83      0.75      0.79        32
justinbieber       0.78      0.85      0.81        33

    accuracy                           0.80        65
   macro avg       0.80      0.80      0.80        65
weighted avg       0.80      0.80      0.80        65

In [25]:
sentences = ["Can't wait for my new album to drop!","Starship is ready for launch!"]

vec = vectorizer.transform(sentences)

print("Logistic Regression:")
print(lr.predict(vec))

print("Naive Bayes:")
print(nb.predict(vec))

Logistic Regression:
['justinbieber' 'elonmusk']
Naive Bayes:
['justinbieber' 'elonmusk']

In [32]:
sentences = ["I just put dick into my ass","I think that im gay"]

vec = vectorizer.transform(sentences)

print("Logistic Regression:")
print(lr.predict(vec))

print("Naive Bayes:")
print(nb.predict(vec))

Logistic Regression:
['elonmusk' 'elonmusk']
Naive Bayes:
['elonmusk' 'elonmusk']

In [26]:
probs = lr.predict_proba(X_test_vec)
preds = lr.predict(X_test_vec)

classes = lr.classes_

for tweet, true_label, pred, prob in zip(X_test, y_test, preds, probs):

    print("Tweet:", tweet)
    print("True:", true_label)
    print("Pred:", pred)
    print(classes[0], prob[0])
    print(classes[1], prob[1])
    print()

Tweet: Ouch my feet!!
True: elonmusk
Pred: justinbieber
elonmusk 0.4193312012819701
justinbieber 0.5806687987180299

Tweet: My second collab with is dropping around the 🌎 tomorrow and it comes with socks
True: justinbieber
Pred: justinbieber
elonmusk 0.47624451787547917
justinbieber 0.5237554821245208

Tweet: On the set of
True: justinbieber
Pred: justinbieber
elonmusk 0.3616632924712879
justinbieber 0.6383367075287121

Tweet: Your album and doc are amazing . So happy and proud of you
True: justinbieber
Pred: justinbieber
elonmusk 0.4942365274328695
justinbieber 0.5057634725671305

Tweet: Watch me perform at The 23rd Annual A Home for the Holidays at this Sunday at 9:30PM ET/9:00PM PT on…
True: justinbieber
Pred: justinbieber
elonmusk 0.47818517078707345
justinbieber 0.5218148292129265

Tweet: Peaches video 9pm PST
True: justinbieber
Pred: justinbieber
elonmusk 0.3410515067916382
justinbieber 0.6589484932083618

Tweet: deamplify means shadowban
True: elonmusk
Pred: elonmusk
elonmusk 0.5073500671676875
justinbieber 0.4926499328323125

Tweet: Going over track listing for the album
True: justinbieber
Pred: justinbieber
elonmusk 0.4761032179850997
justinbieber 0.5238967820149003

Tweet: 📷:
True: justinbieber
Pred: elonmusk
elonmusk 0.5073500671676875
justinbieber 0.4926499328323125

Tweet: No tats for the
True: justinbieber
Pred: elonmusk
elonmusk 0.5958386108411353
justinbieber 0.4041613891588646

Tweet: Friday.
True: justinbieber
Pred: justinbieber
elonmusk 0.3404481017233477
justinbieber 0.6595518982766523

Tweet: Interesting
True: elonmusk
Pred: elonmusk
elonmusk 0.5230131522665191
justinbieber 0.47698684773348093

Tweet: 420
True: elonmusk
Pred: elonmusk
elonmusk 0.5073500671676875
justinbieber 0.4926499328323125

Tweet: Yes, worth noting that accounts you follow on Lists are private
True: elonmusk
Pred: elonmusk
elonmusk 0.5914170312766445
justinbieber 0.4085829687233555

Tweet: Go for the Gold, Ladies!!!!!! Cannot wait to watch some of the best hockey ever!!! We are so proud of you!
True: justinbieber
Pred: elonmusk
elonmusk 0.609098415108184
justinbieber 0.39090158489181603

Tweet: Thank you
True: justinbieber
Pred: justinbieber
elonmusk 0.31864848354296094
justinbieber 0.6813515164570391

Tweet: London Town wif my baby Hailey Bieber
True: justinbieber
Pred: justinbieber
elonmusk 0.4372774374033547
justinbieber 0.5627225625966453

Tweet: 6 DAYS
True: justinbieber
Pred: justinbieber
elonmusk 0.2638639472121702
justinbieber 0.7361360527878298

Tweet: Long day at Twitter HQ with eng team Two significant problems mostly addressed: 1. Fanout service for Following f…
True: elonmusk
Pred: elonmusk
elonmusk 0.5849117921436264
justinbieber 0.4150882078563735

Tweet: Hailey Bieber x 📷:
True: justinbieber
Pred: justinbieber
elonmusk 0.4708228152788547
justinbieber 0.5291771847211453

Tweet: 8 years later &amp; still no laws … 😢
True: elonmusk
Pred: elonmusk
elonmusk 0.5647091559280146
justinbieber 0.4352908440719853

Tweet: .
True: justinbieber
Pred: elonmusk
elonmusk 0.5073500671676875
justinbieber 0.4926499328323125

Tweet: Plaid is sickkk
True: elonmusk
Pred: elonmusk
elonmusk 0.6419690387323995
justinbieber 0.3580309612676005

Tweet: See you live in the metaverse tomorrow 11/18 Sign up:
True: justinbieber
Pred: justinbieber
elonmusk 0.3388136313199016
justinbieber 0.6611863686800984

Tweet: Many go woke for the moral cloak
True: elonmusk
Pred: elonmusk
elonmusk 0.5541026646218847
justinbieber 0.44589733537811527

Tweet: Twitter has been informed by the Turkish government that access will be reenabled shortly
True: elonmusk
Pred: elonmusk
elonmusk 0.6560974649222222
justinbieber 0.34390253507777774

Tweet: Nothing conveys gravitas better than being called Mr. Tweet 🐥
True: elonmusk
Pred: elonmusk
elonmusk 0.5569762897486239
justinbieber 0.44302371025137616

Tweet: One day, Starship will take us to Mars
True: elonmusk
Pred: elonmusk
elonmusk 0.6252716968645415
justinbieber 0.3747283031354585

Tweet: Hopefully, Starship this year
True: elonmusk
Pred: elonmusk
elonmusk 0.5615167361637108
justinbieber 0.43848326383628927

Tweet: ONE WEEK
True: justinbieber
Pred: elonmusk
elonmusk 0.5119024247185456
justinbieber 0.48809757528145437

Tweet: Might need a bit more polish …
True: elonmusk
Pred: elonmusk
elonmusk 0.5467172359029484
justinbieber 0.45328276409705154

Tweet: All four orbital launch pads fully loaded with rockets for the first time!
True: elonmusk
Pred: elonmusk
elonmusk 0.6191156218615935
justinbieber 0.3808843781384065

Tweet: TONIGHT
True: justinbieber
Pred: justinbieber
elonmusk 0.2888073585839521
justinbieber 0.7111926414160479

Tweet: What the Tesla Giga Nevada factory will look like when finished.
True: elonmusk
Pred: elonmusk
elonmusk 0.5958474104064033
justinbieber 0.4041525895935966

Tweet: Tonight 🙏🕊
True: justinbieber
Pred: justinbieber
elonmusk 0.2888073585839521
justinbieber 0.7111926414160479

Tweet: 🐝 all u can🐝
True: elonmusk
Pred: elonmusk
elonmusk 0.5023879005173244
justinbieber 0.4976120994826756

Tweet: Starting today, Twitter will share ad revenue with creators for ads that appear in their reply threads
True: elonmusk
Pred: elonmusk
elonmusk 0.6415495373613443
justinbieber 0.35845046263865565

Tweet: Team turned off 1 engine just before start &amp; 1 stopped itself, so 31 engines fired overall. But still enough engin…
True: elonmusk
Pred: elonmusk
elonmusk 0.6099178437187506
justinbieber 0.3900821562812494

Tweet: It’s not supposed to be real
True: elonmusk
Pred: elonmusk
elonmusk 0.524091939306413
justinbieber 0.475908060693587

Tweet: out now
True: justinbieber
Pred: justinbieber
elonmusk 0.3029452887203582
justinbieber 0.6970547112796418

Tweet: out now
True: justinbieber
Pred: justinbieber
elonmusk 0.3029452887203582
justinbieber 0.6970547112796418

Tweet: 🖤
True: justinbieber
Pred: elonmusk
elonmusk 0.5073500671676875
justinbieber 0.4926499328323125

Tweet: Sped up trip there &amp; back again
True: elonmusk
Pred: elonmusk
elonmusk 0.5094563828613904
justinbieber 0.4905436171386096

Tweet: Nice work by Community Notes team! In general, Community Notes is a game changer for combating wrong information.
True: elonmusk
Pred: elonmusk
elonmusk 0.5987032571478752
justinbieber 0.40129674285212474

Tweet: Don’t worry, just some of my 👽 🛸 friends of mine stopping by …
True: elonmusk
Pred: elonmusk
elonmusk 0.5943641550970975
justinbieber 0.40563584490290255

Tweet: JUSTICE 3/19
True: justinbieber
Pred: justinbieber
elonmusk 0.3052880270933799
justinbieber 0.6947119729066201

Tweet: Another batch of Starlinks in orbit. These will mostly support high latitude connectivity.
True: elonmusk
Pred: elonmusk
elonmusk 0.5731024431800518
justinbieber 0.42689755681994823

Tweet: Thanks for having me the other night in Minneapolis ❤️ what a night
True: justinbieber
Pred: elonmusk
elonmusk 0.5322644208488085
justinbieber 0.46773557915119146

Tweet: what a great day with my boy ! 📷:
True: justinbieber
Pred: justinbieber
elonmusk 0.4888995901490426
justinbieber 0.5111004098509574

Tweet: this Valentine’s Day on my TikTok
True: justinbieber
Pred: justinbieber
elonmusk 0.4925356779662565
justinbieber 0.5074643220337435

Tweet: Elon Musk should
True: elonmusk
Pred: elonmusk
elonmusk 0.5676118981602398
justinbieber 0.43238810183976023

Tweet: STAY OUT NOW
True: justinbieber
Pred: justinbieber
elonmusk 0.3059886585503111
justinbieber 0.6940113414496889

Tweet: If you haven’t peeped the anyone video give it a gander 😘😘😘 thank u for making this video come to life…
True: justinbieber
Pred: justinbieber
elonmusk 0.39115842685805535
justinbieber 0.6088415731419446

Tweet: 📷:
True: justinbieber
Pred: elonmusk
elonmusk 0.5073500671676875
justinbieber 0.4926499328323125

Tweet: You ❤️❤️❤️
True: justinbieber
Pred: justinbieber
elonmusk 0.34044890328054356
justinbieber 0.6595510967194564

Tweet: The countdown begins…
True: justinbieber
Pred: elonmusk
elonmusk 0.5925559302793884
justinbieber 0.4074440697206117

Tweet: The World Economic Forum should control the world
True: elonmusk
Pred: elonmusk
elonmusk 0.5746667816824853
justinbieber 0.4253332183175147

Tweet: In coming months, Twitter will translate &amp; recommend amazing tweets from people in other countries &amp; cultures
True: elonmusk
Pred: elonmusk
elonmusk 0.6641002342846383
justinbieber 0.3358997657153618

Tweet: Changed my name to Mr. Tweet, now Twitter won’t let me change it back 🤣
True: elonmusk
Pred: elonmusk
elonmusk 0.51051245183988
justinbieber 0.4894875481601199

Tweet: BingChatGPT reminds me of Lucky in Waiting for Godot
True: elonmusk
Pred: elonmusk
elonmusk 0.586354477300993
justinbieber 0.413645522699007

Tweet: The Car Aquatic
True: elonmusk
Pred: elonmusk
elonmusk 0.555969992544219
justinbieber 0.444030007455781

Tweet: 👻👻👻👻👻👻👻
True: justinbieber
Pred: elonmusk
elonmusk 0.5073500671676875
justinbieber 0.4926499328323125

Tweet: I feel this one
True: elonmusk
Pred: justinbieber
elonmusk 0.4774485581691731
justinbieber 0.5225514418308269

Tweet: Cybertruck at Tesla Engineering HQ
True: elonmusk
Pred: elonmusk
elonmusk 0.5521400830629604
justinbieber 0.44785991693703964

Tweet: You need the connection but you cant get close
True: justinbieber
Pred: justinbieber
elonmusk 0.4496309717526423
justinbieber 0.5503690282473577